customhost = "employee.cmdmfq9jawrm.us-east-1.rds.amazonaws.com"
customuser = "intellipaat"
custompass = "admin@123"
customdb = "employee"
custombucket = "s3-employee-data"
customregion = "us-east-1"
